### PR TITLE
Display troubleshooting context if update command fails

### LINKED ISSUE #88: Display troubleshooting context if `update` command fails
### Description

Currently, if the `gh valet update` command fails the user will be presented with a pretty opaque message. We should update this to provide insights into what must be done to fix their environment/issue.

#### If user isn't authorized

Current behavior 👇 

```console
$ gh valet update --username mona --password hunter12
Error response from daemon: Get "https://ghcr.io/v2/": denied: denied
```

New behavior 👇 

```console
$ gh valet update --username mona --password hunter12
You are not authorized to access Valet yet. Please ensure you've completed the following:
- Requested access to Valet and received onboarding instructions via email.
- Accepted all of the repository invites sent after being onboarded.
```

#### If token isn't permissive enough

Current behavior 👇 

```console
$ gh valet update --username mona --password valid-pat-without-correct-scopes
Login Succeeded
Error response from daemon: denied
```

New behavior 👇 

```console
$ gh valet update --username mona --password valid-pat-without-correct-scopes
You are not authorized to access Valet yet. Please ensure you've completed the following:
- Requested access to Valet and received onboarding instructions via email.
- Accepted all of the repository invites sent after being onboarded.
- The GitHub personal access token used above contains the 'read:packages' scope.
```

### PR DESCRIPTION
**Pull request by luke-engle**
## What's changing?
When a user runs the update command with an invalid token, the login fails and the user gets a cryptic, unhelpful error message: `Error response from daemon: Get "https://ghcr.io/v2/": denied: denied`

Similarly, when a user runs the update command with a token that doesn't have the required scopes, they get _this_ cryptic error message: `Error response from daemon: denied`

This change addresses this issue by providing the user with clear error messages in these scenarios.

## How's this tested?
Unit tests, and running manually which you can see below 👇 

Invalid token:
```console
➜ echo $INVALID_TOKEN | dotnet run --project src/Valet/Valet.csproj update --username luke-engle --password-stdin
You are not authorized to access Valet yet. Please ensure you've completed the following:
- Requested access to Valet and received onboarding instructions via email.
- Accepted all of the repository invites sent after being onboarded.
```

Invalid scopes:
```console
➜ echo $TOKEN_WITH_INVALID_SCOPES | dotnet run --project src/Valet/Valet.csproj update --username luke-engle --password-stdin
Login Succeeded

Pulling valet-customers/valet-cli:latest from the ghcr.io docker repository...
You are not authorized to access Valet yet. Please ensure you've completed the following:
- Requested access to Valet and received onboarding instructions via email.
- Accepted all of the repository invites sent after being onboarded.
- The GitHub personal access token used above contains the 'read:packages' scope.
```

Closes #88

### CODE REVIEW

File: src/Valet.UnitTests/AppTests.cs [hunk 1]
```diff
@@ -35,7 +35,7 @@ public void AfterEachTest()
     }
 
     [TestCase("4256ea72fd01deac3e967f6b19f907587dcd6f0a976301f1aecc73dc6f146a4a", "4256ea72fd01deac3e967f6b19f907587dcd6f0a976301f1aecc73dc6f146a4a", "")]
-    [TestCase("4256ea72fd01deac3e967f6b19f907587dcd6f0a976301f1aecc73dc6f146a4a", "67eed1493c461efd993be9777598a456562f4e0c6b0bddcb19d819220a06dd4b", "A new version of the Valet CLI is available. Run 'gh valet update' to update.\n")]
+    [TestCase("4256ea72fd01deac3e967f6b19f907587dcd6f0a976301f1aecc73dc6f146a4a", "67eed1493c461efd993be9777598a456562f4e0c6b0bddcb19d819220a06dd4b", $"A new version of the Valet CLI is available. Run 'gh valet update' to update.")]
```
Comment (luke-engle) [inline src/Valet.UnitTests/AppTests.cs:38]: Is the `$` needed here? (I would suggest the change but it isn't letting me for some reason

**Review by dwhathaway — APPROVED** [review]

**Review by NateRickard — APPROVED** [review]

File: src/Valet.UnitTests/AppTests.cs (hunk 1 above)
Comment (NateRickard) [reply src/Valet.UnitTests/AppTests.cs]: Nothing is interpolated within the string, so I would think no.
